<?xml version="1.0" encoding="UTF-8"?><!--(c) 2002, 2012 LANSA--><!--PPC XHTML Standard Cascading Style Sheet--><!--$Workfile:: std_style.xsl $--><!--$UTCDate:: 2013-01-02 22:57:09Z $--><!--$Revision:: 11 $--><xsl:transform version="1.0" exclude-result-prefixes="lxml wd" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:lxml="http://www.lansa.com/2002/XML/Runtime-Data" xmlns:wd="http://www.lansa.com/2002/XSL/Weblet-Design" xmlns="http://www.w3.org/1999/xhtml"><xsl:import href="std_types.xsl"></xsl:import><xsl:import href="std_variables.xsl"></xsl:import><xsl:import href="std_util.xsl"></xsl:import><xsl:template name="style"><xsl:param name="body_bgimage" select="''"></xsl:param><xsl:param name="relative_css_link_filename" select="''"></xsl:param><xsl:variable name="expand_css"></xsl:variable><xsl:call-template name="std_style_emulation_pre.private"></xsl:call-template><link href="{$lweb_style_path}/std_style_lansa_ppc_xhtml.min.css{$expand_css}" type="text/css" rel="stylesheet" charset="utf-8" /><xsl:if test="boolean($relative_css_link_filename)"><xsl:choose><xsl:when test="$relative_css_link_filename = 'std_style_royal_ppc_xhtml.css'"><link href="{$lweb_style_path}/theme_royal_ppc_xhtml.min.css{$expand_css}" type="text/css" rel="stylesheet" charset="utf-8" /></xsl:when><xsl:when test="$relative_css_link_filename = 'std_style_grass_ppc_xhtml.css'"><link href="{$lweb_style_path}/theme_grass_ppc_xhtml.min.css{$expand_css}" type="text/css" rel="stylesheet" charset="utf-8" /></xsl:when><xsl:otherwise><link href="{$lweb_style_path}/{$relative_css_link_filename}{$expand_css}" type="text/css" rel="stylesheet" charset="utf-8" /></xsl:otherwise></xsl:choose></xsl:if><xsl:if test="boolean($lweb_std_css_language_overlay)"><link href="{$lweb_style_path}/{$lweb_std_css_language_overlay}{$expand_css}" type="text/css" rel="stylesheet" /></xsl:if><xsl:apply-templates select="/lxml:data/lxml:external-resources/lxml:style"><xsl:with-param name="expand_css" select="$expand_css"></xsl:with-param></xsl:apply-templates><style type="text/css"><xsl:if test="boolean($body_bgimage)">
				body
				{
				background-image: url("<xsl:value-of select="$lweb_images_path"></xsl:value-of>/<xsl:value-of select="$body_bgimage"></xsl:value-of>");
				}
			</xsl:if>
			.hidden
			{
			display: none;
			}
		</style></xsl:template><xsl:template match="/lxml:data/lxml:external-resources/lxml:style"><xsl:param name="expand_css" select="''"></xsl:param><link href="{$lweb_images_path}/{.}{$expand_css}" type="text/css" rel="stylesheet" charset="{@charset}" /></xsl:template></xsl:transform>